language: node_js

node_js:
  # - '8'
  - '10'

os:
  - linux
  # - osx

cache:
  directories:
    - node_modules

before_install:
  - npm prune
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install expat; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install minizip; fi

before_script:
  - ./scripts/compile_xlsxio.sh

script:
  - npm run compile

after_script:
  - echo "todo run tests"
  - echo "todo copy compiled native modules"

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - git
            - libexpat-dev
            - libminizip-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode8
      env:
        # - MATRIX_EVAL="brew install cmake gcc && CC=gcc-7 && CXX=g++-7"
        - MATRIX_EVAL=""
