# language: node_js

# node_js:
#   - '10'

# cache:
#   directories:
#     - node_modules

# before_install:
#   - npm prune
#   - eval "${MATRIX_EVAL}"
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install expat; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install minizip; fi
#   - node ./scripts/compile_xlsxio.js

# script:
#   - npm run compile

# after_script:
#   - echo "todo run tests"
#   - echo "todo copy compiled native modules"

# matrix:
#   include:
#     - os: linux
#       dist: xenial
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#           packages:
#             - g++-7
#             - cmake
#             - git
#       env:
#         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#     - os: osx
#       osx_image: xcode8
#       env:
#         - MATRIX_EVAL=""
#     - os: windows
#       install:
#         - choco install windows-sdk-10-version-1809-all
#       env:
#         - MSBUILD_PATH="c:/Program Files \(x86\)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
#         - MATRIX_EVAL="export PATH=$MSBUILD_PATH:$PATH"
